global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flower'
    static_configs:
      - targets: ['flower:5555']

  - job_name: '3t_metrics'
    static_configs:
      - targets: ['metrics-exporter:9101']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
